### ISSUE TITLE
you must run the load_ids() method before accessing this property

### ISSUE THREAD

**Issue by ecchirealm** [FujiMakoto/twitter-saucenao#57]
![image](https://user-images.githubusercontent.com/35612417/106073590-976a0c00-60c7-11eb-9892-04377dbb5262.png)

**Comment by FujiMakoto** [comment]
This is probably an issue with the [pysaucenao](https://github.com/FujiMakoto/pysaucenao) library. We're definitely calling the method, so there shouldn't be an exception here.

**Comment by FujiMakoto** [comment]
Should be resolved in https://github.com/FujiMakoto/pysaucenao/commit/b072b5cd71afd4a496604339b2b97960dd7c762e, I'll push a dependency update here and close the issue with the next maintenance release

**Comment by ecchirealm** [comment]
this bug is still showing up for me is there anything I should run to make this work?

**Comment by ecchirealm** [comment]
how do I run load_ids, is there something that should be run first before?

**Comment by FujiMakoto** [comment]
Make sure you run `pip install -r requirements.txt` after pulling the latest release; this fix is in a library, not twitter-saucenao itself

**Comment by ecchirealm** [comment]
yea I already ran that, and went to the pysaucenao library and replaced the container.py with the one you linked but the error is still showing up, I think it has something to do with the load_ids method please message me on twitter, I'll be happy to pay you for your help :)
